### ISSUE TITLE
Namespace error

### ISSUE THREAD

**Issue by Cecil160** [TheLonelyGhost/vault-exporter#1]
We are using Vault Enterprise but currently have no namespaces configured.  

When I attempt to run the script, I receive an hvac exception "hvac.exceptions.InvalidPath: None".  

Is the script expecting namespaces to exist? 

How hard would it be to refactor for no namespaces if that is the problem?

Full Error:

```
Traceback (most recent call last):
  File "Documents/Codes/Python/exporter/export_kv_secrets.py", line 101, in <module>
    main()
  File "Documents/Codes/Python/exporter/export_kv_secrets.py", line 91, in main
    namespaces = [''] + list_namespaces(client)  # root namespace and underlings
  File "Documents/Codes/Python/exporter/export_kv_secrets.py", line 64, in list_namespaces
    result = client.sys.list_namespaces()['data']
  File "/Users/<user>/venv/lib/python3.8/site-packages/hvac/api/system_backend/namespace.py", line 31, in list_namespaces
    return self._adapter.list(
  File "/Users/<user>/venv/lib/python3.8/site-packages/hvac/adapters.py", line 146, in list
    return self.request('list', url, **kwargs)
  File "/Users/<user>/venv/lib/python3.8/site-packages/hvac/adapters.py", line 336, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/Users/<user>/venv/lib/python3.8/site-packages/hvac/adapters.py", line 304, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/Users/<user>/venv/lib/python3.8/site-packages/hvac/utils.py", line 38, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors)
hvac.exceptions.InvalidPath: None
```

**Comment by Cecil160** [comment]
original:
```
namespaces = [''] + list_namespaces(client) # root namespace and underlings
```

modified:
```
namespaces = [''] #+ list_namespaces(client) # root namespace and underlings
```

With this modification, the script now retrieves all kv1 secrets successfully but generates an error while retrieving kv2 secrets:

```
Traceback (most recent call last):
  File "/Users/removed/Documents/Codes/Python/exporter/export_kv_secrets.py", line 101, in <module>
    main()
  File "/Users/removed/Documents/Codes/Python/exporter/export_kv_secrets.py", line 97, in main
    export_secrets(client=ns_client, namespace=namespace, local_path=str(tmp_dir))
  File "/Users/removed/Documents/Codes/Python/exporter/export_kv_secrets.py", line 83, in export_secrets
    f.write(json.dumps(read_secret(client=client, path=path, mount=mount, version=version)))
  File "/Users/removed/Documents/Codes/Python/exporter/export_kv_secrets.py", line 52, in read_secret
    result = client.secrets.kv.v2.read_secret_version(path=path, mount_point=mount)['data']['data']
  File "/Users/removed/venv/lib/python3.8/site-packages/hvac/api/secrets_engines/kv_v2.py", line 83, in read_secret_version
    return self._adapter.get(
  File "/Users/removed/venv/lib/python3.8/site-packages/hvac/adapters.py", line 94, in get
    return self.request('get', url, **kwargs)
  File "/Users/removed/venv/lib/python3.8/site-packages/hvac/adapters.py", line 336, in request
    response = super(JSONAdapter, self).request(*args, **kwargs)
  File "/Users/removed/venv/lib/python3.8/site-packages/hvac/adapters.py", line 304, in request
    utils.raise_for_error(response.status_code, text, errors=errors)
  File "/Users/removed/venv/lib/python3.8/site-packages/hvac/utils.py", line 38, in raise_for_error
    raise exceptions.InvalidPath(message, errors=errors)
hvac.exceptions.InvalidPath: {"request_id":"removed","lease_id":"","renewable":false,"lease_duration":0,"data":{"data":null,"metadata":{"created_time":"2019-07-09T22:07:15.392741636Z","deletion_time":"2019-07-09T22:15:44.567305994Z","destroyed":false,"version":1}},"wrap_info":null,"warnings":null,"auth":null}
```

**Comment by Cecil160** [comment]
The new error was due to a secret whose value had been deleted without removing the secret itself.  It appears that the script didn't know how to continue with a null value and no previous version of the secret to retrieve.  To get past this issue, I deleted the null secret and the script now runs as expected.

Others who try to use this script without namespaces defined in their Vault cluster will need to modify line 91 as noted above.

@TheLonelyGhost Thanks so much for building this script and making it available to us!!  I have been trying to piece together a script to retrieve my secrets as a safety net before revoking some tokens in our environment with minimal success.  You rock!

**Comment by TheLonelyGhost** [comment]
I'm reopening this issue if only because I expected it to work regardless of namespaces being used. I'll have to tinker a bit to confirm, but I suspect this might be fixed with a `try` / `except` when populating the namespaces.

Definitely glad you found some use out of it! I'm interested in your use case where the value was null and the secret still existed. How did it get that way?

**Comment by Cecil160** [comment]
Yeah, I think the try/except could work too but wasn't exactly sure where/how to implement.

As to the null secret value...
I give individual development teams their own policies that allow them to completely manage secrets within their specific paths (like a poor man's OSS attempt at getting around need for namespaces).

The development teams know nothing about vault past the little how-to blurb that I send them when providing them with their credentials and pathing structure.

It would appear that either a problem exists with their policy that prevents them from deleting the secret itself but allows deleting the versions/values or they just completely did it wrong.  Not sure which yet, but am investigating because I am also curious. :-)

**Comment by TheLonelyGhost** [comment]
Okay, I think I've pushed a version of the code that should work for your cases. I suspect the null value for a KV secret is a bug in Vault itself, but even so this tool should accommodate it by skipping the export of a null secret.

If you get more info on how it was created, I'd love to hear it. My team is in a similar situation with multi-team use of vault with very little instruction to the teams.

**Comment by Cecil160** [comment]
Thanks!  I have already deleted the two secrets with null values and am currently attempting to recreate that problem using a token I generated with their policy.  I will take a look at your modifications in a bit and confirm that they resolve the no namespace issue at the very least.

**Comment by Cecil160** [comment]
1) Confirmed that the updated script works with no defined namespaces.
2) Confirmed that null secrets do not generate an error.
3) Determined how the null secrets happened.  In a KVv2 secret, if you send DELETE to /secret/data/:path the latest version of the secret will be deleted, but not the secret itself (even if there is only one version).  To delete the secret itself, you must send DELETE to /secret/metadata/:path.  I will update the documentation I send to the dev teams to prevent this confusion in the future.
4) Thanks for your assistance and the quick updates!
